services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_watch_tower
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d my_watch_tower" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:9.10
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      # PGADMIN_PGPASSFILE: /.pgpass # tried setting automatic login, can't work no matter what
    ports:
      - "8080:80"
    volumes:
      - ./docker-confs/pgadmin-servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  backend:
    image: my-watch-tower-backend:latest
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    env_file: "./backend/.env.docker.sample"
    # ports:
    #   - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
  backend-migrate:
    image: my-watch-tower-backend:latest
    build:
      context: ./backend
    command: [ "sh", "-c", 'npx prisma migrate deploy' ]
    env_file: "./backend/.env.docker.sample"
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    image: my-watch-tower-frontend:latest
    build:
      context: ./frontend
    # env_file: "./frontend/.env"
    # ports:
    #   - "5173:5173"
    depends_on:
      backend:
        condition: service_started
  nginx:
    image: nginx:1.28
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker-confs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
volumes:
  postgres_data:
    driver: local
