/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */

export type GetSatellitesParams = {
/**
 * Fetch only tracked satellites?
 */
tracked?: string;
/**
 * Filter by tag name
 */
tag?: string;
/**
 * Filter by (part of) satellite name, case insensitive
 */
name?: string;
/**
 * JSON stringified array of frequency filter objects: [ {"min": number, "max": number, "direction": "downlink" | "uplink" } ]
 */
frequencyFilters?: string;
page?: string;
};
