/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */
import type { SatelliteEntity } from './satelliteEntity';

export interface PassEventEntity {
  id: number;
  groundStationId: number;
  satelliteId: number;
  satellite: SatelliteEntity;
  orbitNumber: number;
  aos: string;
  los: string;
  maxElevation: number;
  duration: number;
  visibleSegments: string;
  totalVisibleDuration: number;
  maxVisibleElevation: number;
  createdAt: string;
  updatedAt: string;
}
