/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */

export interface SatelliteEntity {
  id: number;
  name: string;
  noradId: number;
  catalogNumber: number;
  internationalDesignator: string;
  launchDate: string;
  isTracked: boolean;
  createdAt: string;
  updatedAt: string;
  line1: string;
  line2: string;
  sourceId: number;
}
