/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */
import type { SatelliteEntity } from './satelliteEntity';

export interface SatelliteEntityResponse {
  items: SatelliteEntity[];
  total: number;
  page: number;
  pageCount: number;
}
