/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */

export interface TransmitterEntity {
  id: number;
  /** @nullable */
  description: string | null;
  /** @nullable */
  type: string | null;
  /** @nullable */
  status: string | null;
  /** @nullable */
  uplinkLow: number | null;
  /** @nullable */
  uplinkHigh: number | null;
  /** @nullable */
  downlinkLow: number | null;
  /** @nullable */
  downlinkHigh: number | null;
  /** @nullable */
  mode: string | null;
  /** @nullable */
  baud: number | null;
  invert: boolean;
  /** @nullable */
  citation: string | null;
}
