/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */
import type { TransmitterEntityDescription } from './transmitterEntityDescription';
import type { TransmitterEntityType } from './transmitterEntityType';
import type { TransmitterEntityStatus } from './transmitterEntityStatus';
import type { TransmitterEntityUplinkLow } from './transmitterEntityUplinkLow';
import type { TransmitterEntityUplinkHigh } from './transmitterEntityUplinkHigh';
import type { TransmitterEntityDownlinkLow } from './transmitterEntityDownlinkLow';
import type { TransmitterEntityDownlinkHigh } from './transmitterEntityDownlinkHigh';
import type { TransmitterEntityMode } from './transmitterEntityMode';
import type { TransmitterEntityBaud } from './transmitterEntityBaud';
import type { TransmitterEntityCitation } from './transmitterEntityCitation';

export interface TransmitterEntity {
  id: number;
  description: TransmitterEntityDescription;
  type: TransmitterEntityType;
  status: TransmitterEntityStatus;
  uplinkLow: TransmitterEntityUplinkLow;
  uplinkHigh: TransmitterEntityUplinkHigh;
  downlinkLow: TransmitterEntityDownlinkLow;
  downlinkHigh: TransmitterEntityDownlinkHigh;
  mode: TransmitterEntityMode;
  baud: TransmitterEntityBaud;
  invert: boolean;
  citation: TransmitterEntityCitation;
}
