/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */

export type TransmitterEntityStatus = { [key: string]: unknown };
