/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My Watch Tower API
 * Satellite tracker and predictor
 * OpenAPI spec version: 1.0
 */

export interface UpdateGroundStationDto {
  name?: string;
  latitude?: number;
  longitude?: number;
  altitude?: number;
  horizonmask?: string;
}
